steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use the Cloud SDK Docker image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Copy the file to GCP bucket
        gsutil cp ..test.txt gs://project-dev-cloudresumechallenge2024

# Optional: Specify a timeout for the build
timeout: '600s'
