steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use the Cloud SDK Docker image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd Website
        # Copy the file to GCP bucket
        gsutil -m cp -r gs://project-dev-cloudresumechallenge2024
        

# Optional: Specify a timeout for the build
timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
